language: go
go:
- 1.13
os:
- linux
install:
- export VERSION_ETCD="3.3.10"
- wget -q -O /tmp/etcd.tar.gz "https://github.com/etcd-io/etcd/releases/download/v$VERSION_ETCD/etcd-v$VERSION_ETCD-linux-amd64.tar.gz"
- tar xvzf /tmp/etcd.tar.gz -C /tmp
- export PATH="$PATH:/tmp/etcd-v$VERSION_ETCD-linux-amd64"
script:
- go test .
